name: Slack Notification

on:
  schedule:
    - cron: '00 08 * * 5'

jobs:
  slack-bot:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Restore cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Notification
        run: node_modules/.bin/slack-updates-bot --url ${{ secrets.SLACK_WEBHOOK_URL }}
